package `in`.bikecourierservice.driver

import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * FullScreenOrderAlertModule
 *
 * React Native native module (Android only) that posts a full-screen urgent
 * notification capable of waking the screen and displaying over the lock screen.
 *
 * Exposed to JS as NativeModules.FullScreenOrderAlert with two methods:
 *   showAlert(orderId, title, body)  — posts the notification
 *   cancelAlert()                    — cancels notification ID 9001
 *
 * Design notes
 * ────────────
 * • Posts to the existing "incoming_orders_v2" channel, which is created by
 *   expo-notifications (setupAndroidChannels in notifications.ts) with MAX
 *   importance, ringtone sound, bypassDnd, and the correct vibration pattern.
 *   On Android 8+ channel settings override per-notification builder settings
 *   for sound and vibration, so we do NOT set sound on the builder. We DO set
 *   vibrate() as a signal to older devices and as a belt-and-suspenders fallback.
 * • setFullScreenIntent(fullScreenPending, true) — the "true" flag marks this
 *   as high-priority and requests the system to invoke the intent immediately
 *   when the device is locked, bypassing the notification shade.
 * • Category: CATEGORY_TRANSPORT (Play Store safe for courier / delivery apps).
 * • Visibility: VISIBILITY_PUBLIC so the notification is fully visible on the
 *   lock screen without requiring PIN/biometric.
 * • No SYSTEM_ALERT_WINDOW permission is used or required.
 * • The small icon resolves "ic_notification" (generated by expo-notifications
 *   plugin from the icon asset) with a fallback to a system dialog icon.
 */
class FullScreenOrderAlertModule(
    private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = MODULE_NAME

    /**
     * Post the full-screen order alert notification.
     *
     * @param orderId Firestore order document ID — embedded in all deep-link URIs.
     * @param title   Notification title (e.g. "🛵 New Delivery Request").
     * @param body    Notification body (e.g. "Andheri → Bandra • ₹180 • 4.2 km").
     * @param promise Resolved with null on success; rejected with an error on failure.
     */
    @ReactMethod
    fun showAlert(orderId: String, title: String, body: String, promise: Promise) {
        try {
            val ctx = reactContext.applicationContext

            // ── Tap intent: notification body tap → ride-request screen ───────
            // deep-link scheme "mobile" matches app.json scheme field.
            val tapUri = Uri.parse("mobile://ride-request?orderId=${Uri.encode(orderId)}")
            val tapIntent = Intent(Intent.ACTION_VIEW, tapUri).apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
                setPackage(ctx.packageName)
            }
            val tapPending = PendingIntent.getActivity(
                ctx,
                orderId.hashCode(),
                tapIntent,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )

            // ── Full-screen intent: explicit MainActivity launch ──────────────
            // Must target MainActivity by class (not a deep-link URI) so the OS
            // can start the Activity before the JS bridge is up on a killed/locked
            // device.  orderId is passed as an extra; FLAG_ACTIVITY_NEW_TASK and
            // FLAG_ACTIVITY_CLEAR_TOP are kept so an existing task is reused.
            val fullScreenIntent = Intent(ctx, MainActivity::class.java).apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
                putExtra("orderId", orderId)
            }
            val fullScreenPending = PendingIntent.getActivity(
                ctx,
                orderId.hashCode() + 3,
                fullScreenIntent,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )

            // ── Accept action button ───────────────────────────────────────────
            val acceptIntent = Intent(ctx, FullScreenOrderActionReceiver::class.java).apply {
                action = FullScreenOrderActionReceiver.ACTION_ACCEPT
                putExtra(FullScreenOrderActionReceiver.EXTRA_ORDER_ID, orderId)
            }
            val acceptPending = PendingIntent.getBroadcast(
                ctx,
                orderId.hashCode() + 1,
                acceptIntent,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )

            // ── Reject action button ───────────────────────────────────────────
            val rejectIntent = Intent(ctx, FullScreenOrderActionReceiver::class.java).apply {
                action = FullScreenOrderActionReceiver.ACTION_REJECT
                putExtra(FullScreenOrderActionReceiver.EXTRA_ORDER_ID, orderId)
            }
            val rejectPending = PendingIntent.getBroadcast(
                ctx,
                orderId.hashCode() + 2,
                rejectIntent,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )

            // ── Small icon ────────────────────────────────────────────────────
            // expo-notifications plugin generates "ic_notification" from the app icon.
            // Fall back to the system dialog icon if neither resource exists.
            val iconResId =
                ctx.resources.getIdentifier("ic_notification", "drawable", ctx.packageName)
                    .takeIf { it != 0 }
                    ?: ctx.resources.getIdentifier(
                        "notification_icon", "drawable", ctx.packageName,
                    ).takeIf { it != 0 }
                    ?: android.R.drawable.ic_dialog_info

            // ── Notification ──────────────────────────────────────────────────
            val notification = NotificationCompat.Builder(ctx, CHANNEL_ID)
                .setSmallIcon(iconResId)
                .setContentTitle(title)
                .setContentText(body)
                .setPriority(NotificationCompat.PRIORITY_MAX)
                .setCategory(NotificationCompat.CATEGORY_CALL)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                .setAutoCancel(false)
                .setOngoing(false)
                // Vibration pattern matches the 5 canonical locations in the codebase.
                // On Android 8+ this is overridden by channel settings — it acts as
                // a belt-and-suspenders fallback for older API levels.
                .setVibrate(longArrayOf(0, 1200, 200, 1200, 200, 1200, 500))
                // Sound is NOT set on the builder — the channel already has the
                // custom ringtone configured by setupAndroidChannels().
                .setFullScreenIntent(fullScreenPending, true)
                .setContentIntent(tapPending)
                .addAction(
                    android.R.drawable.ic_input_add,
                    "✅  Accept",
                    acceptPending,
                )
                .addAction(
                    android.R.drawable.ic_delete,
                    "❌  Reject",
                    rejectPending,
                )
                .build()

            NotificationManagerCompat.from(ctx).notify(NOTIFICATION_ID, notification)
            promise.resolve(null)
        } catch (e: Exception) {
            promise.reject("FSA_SHOW_ERROR", e.message ?: "Unknown error posting alert", e)
        }
    }

    /**
     * Cancel the active full-screen order alert (notification ID 9001).
     * Safe to call even when no alert is showing.
     */
    @ReactMethod
    fun cancelAlert(promise: Promise) {
        try {
            val nm = reactContext.getSystemService(Context.NOTIFICATION_SERVICE)
                as NotificationManager
            nm.cancel(NOTIFICATION_ID)
            promise.resolve(null)
        } catch (e: Exception) {
            promise.reject("FSA_CANCEL_ERROR", e.message ?: "Unknown error cancelling alert", e)
        }
    }

    // Required stubs for React Native's NativeEventEmitter compatibility.
    // This module does not emit events — stubs prevent "not supported" warnings.
    @ReactMethod fun addListener(@Suppress("UNUSED_PARAMETER") eventName: String) {}
    @ReactMethod fun removeListeners(@Suppress("UNUSED_PARAMETER") count: Int) {}

    companion object {
        const val MODULE_NAME     = "FullScreenOrderAlert"
        const val CHANNEL_ID      = "incoming_orders_v2"  // must match CHANNEL_ORDERS in notifications.ts
        const val NOTIFICATION_ID = 9001
    }
}
