kind = "web"
previewPath = "/admin/"
title = "Driver Management"
version = "1.0.0"
id = "artifacts/admin-panel"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/admin/" ]
localPort = 8082

[services.env]
PORT = "8082"
BASE_PATH = "/admin/"

[services.development]
run = "pnpm --filter @workspace/admin-panel run dev"
