import {
  arrayUnion,
  collection,
  doc,
  getDoc,
  getDocs,
  onSnapshot,
  query,
  runTransaction,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
} from "firebase/firestore";
import { db } from "./firebase";
import type { Profile, Vehicle } from "@/contexts/DriverContext";

// ─── Driver doc ───────────────────────────────────────────────────────────────

export type DriverDoc = {
  uid:                    string;
  phone:                  string;
  name?:                  string;
  city?:                  string;
  gender?:                string;
  vehicleId?:             string;
  vehicleName?:           string;
  isOnline:               boolean;
  subscriptionPlan?:      string;
  subscriptionExpiresAt?: number;
  createdAt:              unknown;
};

export async function getDriverDoc(uid: string): Promise<DriverDoc | null> {
  const snap = await getDoc(doc(db, "drivers", uid));
  return snap.exists() ? (snap.data() as DriverDoc) : null;
}

export async function createDriverDoc(uid: string, phone: string): Promise<DriverDoc> {
  const data: Omit<DriverDoc, "createdAt"> & { createdAt: unknown } = {
    uid,
    phone,
    isOnline:  false,
    createdAt: serverTimestamp(),
  };
  await setDoc(doc(db, "drivers", uid), data, { merge: true });
  return { ...data, createdAt: Date.now() };
}

export async function updateDriverProfile(uid: string, p: Profile): Promise<void> {
  await setDoc(doc(db, "drivers", uid), {
    name:      p.name,
    city:      p.city,
    gender:    p.gender,
    updatedAt: serverTimestamp(),
  }, { merge: true });
}

export async function updateDriverVehicle(uid: string, v: Vehicle): Promise<void> {
  await setDoc(doc(db, "drivers", uid), {
    vehicleId:   v.id,
    vehicleName: v.name,
    updatedAt:   serverTimestamp(),
  }, { merge: true });
}

/**
 * Persist the driver's active subscription so it survives app restarts.
 * Called by activatePlan() in DriverContext.
 */
export async function updateDriverSubscription(
  uid:                  string,
  plan:                 string,
  subscriptionExpiresAt: number,
): Promise<void> {
  await setDoc(doc(db, "drivers", uid), {
    subscriptionPlan:      plan,
    subscriptionExpiresAt,
    updatedAt:             serverTimestamp(),
  }, { merge: true });
}

/**
 * Mark the driver's document submission in Firestore.
 * Does NOT upload images — only writes submission metadata.
 * Called by document-upload.tsx after all 5 docs are selected locally.
 */
export async function submitDriverDocuments(uid: string): Promise<void> {
  await setDoc(doc(db, "drivers", uid), {
    documentsSubmitted:   true,
    verificationStatus:   "pending",
    documentsSubmittedAt: serverTimestamp(),
    updatedAt:            serverTimestamp(),
  }, { merge: true });
}

/**
 * Persist the driver's online/offline status so the customer app and
 * dispatcher can filter available drivers.
 */
export async function updateDriverOnlineStatus(
  uid:      string,
  isOnline: boolean,
): Promise<void> {
  await setDoc(doc(db, "drivers", uid), {
    isOnline,
    updatedAt: serverTimestamp(),
  }, { merge: true });
}

// ─── Order doc ────────────────────────────────────────────────────────────────
//
// Firestore collection: "orders"
// Document ID: auto-generated by the customer app.
//
// Lifecycle written by each party:
//   Customer app  → creates doc, sets status="dispatched", driverUid=<uid>
//   Driver app    → updates status through the stage machine below
//
// Required Firestore composite index (created automatically on first query;
// Firestore prints the console link):
//   Collection: orders  |  Fields: driverUid ASC, status ASC
//
// Stage machine:
//   dispatched → accepted → to_pickup → at_pickup → to_drop → at_drop → delivered
//   Any stage  → rejected  (driver declines)
//   Any stage  → cancelled (customer cancels)

export type OrderStatus =
  | "pending"
  | "dispatched"
  | "accepted"
  | "rejected"
  | "to_pickup"
  | "at_pickup"
  | "to_drop"
  | "at_drop"
  | "delivered"
  | "cancelled";

export type OrderDoc = {
  id:               string;
  status:           OrderStatus;
  driverUid:        string | null;

  // Customer identity
  customerId:       string;
  customerName:     string;
  customerPhone:    string;
  customerRating:   number;

  // Parcel
  parcelType:       string;
  parcelEmoji:      string;
  parcelWeight:     string;

  // Route
  pickup:           string;
  pickupSub?:       string;
  pickupCity:       string;
  drop:             string;
  dropSub?:         string;
  dropCity:         string;
  distanceKm:       number;
  pickupDistanceKm?: number;
  durationMin:      number;

  // Fare
  fareEstimate:     number;
  paymentMode:      "Cash" | "UPI" | "Card";
  surge?:           boolean;
  surgeMultiplier?: number;

  // Timestamps — set by serverTimestamp() at each transition
  createdAt:    unknown;
  dispatchedAt?: unknown;
  acceptedAt?:  unknown;
  rejectedAt?:  unknown;
  to_pickupAt?: unknown;
  at_pickupAt?: unknown;
  to_dropAt?:   unknown;
  at_dropAt?:   unknown;
  deliveredAt?: unknown;

  // Rejection history — dispatcher reads to avoid re-assigning the same driver
  rejectedBy?: string[];

  // Written by driver on accept
  driverName?:    string;

  // Generated by customer app when order is created; driver must verify at drop
  deliveryOtp?:   string;
};

/**
 * Listen for the single "dispatched" order assigned to this driver.
 * The customer app sets { status: "dispatched", driverUid: uid } to trigger this.
 * Returns an unsubscribe function; call it on cleanup.
 */
export function listenToDispatchedOrder(
  uid:     string,
  onOrder: (order: OrderDoc | null) => void,
): () => void {
  const q = query(
    collection(db, "orders"),
    where("driverUid", "==", uid),
    where("status",    "==", "dispatched"),
  );
  return onSnapshot(q, (snap) => {
    if (snap.empty) {
      onOrder(null);
    } else {
      const docSnap = snap.docs[0]!;
      onOrder({ id: docSnap.id, ...docSnap.data() } as OrderDoc);
    }
  });
}

/**
 * Subscribe to a single order document.
 * Calls back with the live status string, or null if the doc no longer exists.
 * Returns an unsubscribe function; call it on cleanup.
 */
export function listenToActiveOrder(
  orderId:  string,
  onChange: (status: OrderStatus | null) => void,
): () => void {
  return onSnapshot(doc(db, "orders", orderId), (snap) => {
    if (!snap.exists()) {
      onChange(null);
      return;
    }
    onChange((snap.data() as OrderDoc).status);
  });
}

/**
 * Return the single in-progress order assigned to this driver, or null.
 * Queries by driverUid only (no composite index needed), then filters
 * active statuses client-side.
 */
const ACTIVE_STATUSES = new Set<OrderStatus>([
  "accepted", "to_pickup", "at_pickup", "to_drop", "at_drop",
]);

export async function getActiveOrderForDriver(uid: string): Promise<OrderDoc | null> {
  const snap = await getDocs(
    query(collection(db, "orders"), where("driverUid", "==", uid)),
  );
  const active = snap.docs
    .map((d) => ({ id: d.id, ...d.data() } as OrderDoc))
    .filter((o) => ACTIVE_STATUSES.has(o.status));
  if (active.length === 0) return null;
  active.sort((a, b) => {
    const ta = (a.acceptedAt as { toMillis?: () => number })?.toMillis?.() ?? 0;
    const tb = (b.acceptedAt as { toMillis?: () => number })?.toMillis?.() ?? 0;
    return tb - ta;
  });
  return active[0]!;
}

/**
 * Typed result returned by the atomic acceptOrder transaction.
 *
 * ok: true  — transaction succeeded; this driver now owns the order.
 * ok: false — transaction aborted; reason tells the caller why:
 *   "already_claimed" — order was accepted by this driver on another code path
 *   "reassigned"      — order driverUid no longer matches this driver
 *   "not_dispatched"  — order status has moved past "dispatched"
 *   "missing"         — order document does not exist
 *   "unknown"         — unexpected Firestore error
 */
export type AcceptOrderResult =
  | { ok: true }
  | { ok: false; reason: "already_claimed" | "reassigned" | "not_dispatched" | "missing" | "unknown" };

/**
 * Atomically claim a dispatched order for this driver.
 *
 * Uses a Firestore runTransaction so exactly one driver wins when multiple
 * drivers (or multiple code paths on the same device) call this concurrently:
 *   • Reads the order doc inside the transaction.
 *   • Aborts if the doc is missing, the status is no longer "dispatched",
 *     or the driverUid has been reassigned to a different driver.
 *   • Writes status="accepted", driverUid, driverName, acceptedAt, updatedAt
 *     only when all pre-conditions pass.
 *
 * Returns AcceptOrderResult — callers MUST check result.ok before updating
 * local state.  Never set activeOrders until this returns { ok: true }.
 */
export async function acceptOrder(
  orderId:    string,
  driverUid:  string,
  driverName: string | null,
): Promise<AcceptOrderResult> {
  try {
    await runTransaction(db, async (tx) => {
      const ref  = doc(db, "orders", orderId);
      const snap = await tx.get(ref);

      if (!snap.exists()) {
        throw Object.assign(new Error("Order document missing"), { code: "missing" });
      }

      const data = snap.data() as OrderDoc;

      // Order must still be waiting for a driver.
      if (data.status !== "dispatched") {
        // Distinguish "this driver already accepted on another path" vs
        // "a different driver claimed it" vs "customer cancelled / timed out".
        const sameDriver = data.driverUid === driverUid;
        throw Object.assign(new Error("Order no longer dispatched"), {
          code: sameDriver ? "already_claimed" : "not_dispatched",
        });
      }

      // Order must still be assigned to this driver (not reassigned by dispatcher).
      if (data.driverUid !== driverUid) {
        throw Object.assign(new Error("Order reassigned to another driver"), { code: "reassigned" });
      }

      tx.update(ref, {
        status:     "accepted",
        driverUid,
        driverName: driverName ?? "",
        acceptedAt: serverTimestamp(),
        updatedAt:  serverTimestamp(),
      });
    });

    return { ok: true };
  } catch (e: unknown) {
    const code = (e as { code?: string }).code;
    if (code === "already_claimed") return { ok: false, reason: "already_claimed" };
    if (code === "reassigned")      return { ok: false, reason: "reassigned" };
    if (code === "missing")         return { ok: false, reason: "missing" };
    if (code === "not_dispatched")  return { ok: false, reason: "not_dispatched" };
    return { ok: false, reason: "unknown" };
  }
}

/**
 * Driver rejects a dispatched order.
 * Appends driverUid to rejectedBy[] so the dispatcher can reassign to another driver.
 */
export async function rejectOrder(orderId: string, driverUid: string): Promise<void> {
  await updateDoc(doc(db, "orders", orderId), {
    status:     "rejected",
    rejectedAt: serverTimestamp(),
    rejectedBy: arrayUnion(driverUid),
  });
}

/**
 * Write the current delivery stage into the order document.
 * Called by active-delivery.tsx on each stage advance so the customer app
 * can track progress in real time.
 */
export type DeliveryStage = "to_pickup" | "at_pickup" | "to_drop" | "at_drop" | "delivered";

export async function updateOrderStage(
  orderId: string,
  stage:   DeliveryStage,
): Promise<void> {
  await updateDoc(doc(db, "orders", orderId), {
    status:          stage,
    [`${stage}At`]:  serverTimestamp(),
  });
}
